import { useRef, useState } from 'react';
import { apiFetch, formatMoney } from '../lib/api';
const empty={cliente_nome:'',cliente_telefone:'',quantidade:'',descricao:'',preco_unitario:'',valor_total:'',valor_pago:'',desconto:'',data_pedido:'',data_entrega:''};
export function AvulsoForm({onSaved,onPrint}:{onSaved:()=>void;onPrint:(id:string)=>void}){
 const [form,setForm]=useState(empty);const [saving,setSaving]=useState(false);const [saved,setSaved]=useState<any>(null);const attempt=useRef({fingerprint:'',key:''});const busy=useRef(false);
 const qty=Number(form.quantidade)||1;const gross=form.valor_total!==''?Number(form.valor_total):qty*(Number(form.preco_unitario)||0);const discount=Math.min(Number(form.desconto)||0,gross);const total=Math.max(0,gross-discount);const paid=Math.min(Number(form.valor_pago)||0,total);const remaining=Math.max(0,total-paid);
 function update(key:keyof typeof empty,value:string){setForm(prev=>({...prev,[key]:value,...(['preco_unitario','quantidade'].includes(key)?{valor_total:''}:{})}));}
 async function save(){if(busy.current)return;busy.current=true;setSaving(true);const fingerprint=JSON.stringify(form);if(attempt.current.fingerprint!==fingerprint)attempt.current={fingerprint,key:crypto.randomUUID()};try{const order=await apiFetch('/admin/pdv/avulso',{method:'POST',body:JSON.stringify({...form,chave_checkout:attempt.current.key})});setSaved(order);onSaved();}catch(e:any){alert(e.message||'Falha ao salvar pedido.');}finally{busy.current=false;setSaving(false);}}
 if(saved)return <div className="card p-6 space-y-4"><h2 className="font-bold text-xl">Pedido {saved.numero_pedido} registrado</h2><p>Total: {formatMoney(saved.total)} · Restante: {formatMoney(saved.valor_restante)}</p><div className="flex flex-wrap gap-3"><button className="btn btn-primary" onClick={()=>onPrint(saved.id)}>Imprimir na Elgin L42 Pro</button><button className="btn btn-outline" onClick={()=>{setSaved(null);setForm(empty);attempt.current={fingerprint:'',key:''};}}>Novo pedido avulso</button></div></div>;
 return <form className="card p-4 sm:p-6 space-y-4" onSubmit={e=>{e.preventDefault();save();}}><h2 className="text-xl font-bold text-primary">Pedido avulso</h2><p className="text-sm text-gray-500">Todos os campos são opcionais. Você pode registrar um pedido sem produto cadastrado.</p><fieldset disabled={saving} className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{([{key:'cliente_nome',label:'Cliente',type:'text'},{key:'cliente_telefone',label:'WhatsApp',type:'tel'},{key:'quantidade',label:'Quantidade',type:'number'},{key:'preco_unitario',label:'Valor unitário',type:'number'},{key:'valor_total',label:'Total antes do desconto',type:'number'},{key:'desconto',label:'Desconto',type:'number'},{key:'valor_pago',label:'Valor pago',type:'number'},{key:'data_pedido',label:'Data do pedido',type:'date'},{key:'data_entrega',label:'Data de entrega',type:'date'}] as const).map(f=><label key={f.key} className="text-sm font-semibold">{f.label}<input className="input mt-1" type={f.type} min={f.key==='quantidade'?1:0} step={f.key==='quantidade'?1:f.type==='number'?'0.01':undefined} value={form[f.key]} placeholder={f.key==='quantidade'?'1':f.key==='valor_total'?gross.toFixed(2):''} onChange={e=>update(f.key,e.target.value)}/></label>)}<label className="sm:col-span-2 lg:col-span-3 text-sm font-semibold">Descrição<textarea className="input mt-1" rows={3} value={form.descricao} onChange={e=>update('descricao',e.target.value)}/></label></fieldset><p className="text-xs text-gray-500">Sem quantidade, será considerada 1 unidade. Sem data, será usada a data atual. O total informado prevalece sobre quantidade × valor unitário.</p><div className="grid grid-cols-3 gap-3 bg-primary text-white p-4 rounded-xl"><div><p className="text-xs">Total</p><b>{formatMoney(total)}</b></div><div><p className="text-xs">Pago</p><b>{formatMoney(paid)}</b></div><div><p className="text-xs">Restante</p><b>{formatMoney(remaining)}</b></div></div>{Number(form.valor_pago)>total&&<p className="text-sm">O valor registrado como pago será limitado ao total do pedido.</p>}<button className="btn btn-primary" disabled={saving}>{saving?'Salvando…':'Salvar pedido avulso'}</button></form>;
}
