import { useState } from 'react';
import { apiFetch } from '../lib/api';

async function upload(file:File) {
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)) throw new Error('Use imagens JPEG, PNG ou WebP.');
 if(file.size>20000000) throw new Error('Cada imagem deve ter até 20 MB.');
 const bitmap=await createImageBitmap(file);
 const scale=Math.min(1,1920/Math.max(bitmap.width,bitmap.height));
 const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));
 canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
 const data=canvas.toDataURL('image/webp',.85);
 if(data.length>1900000)throw new Error('Imagem muito detalhada. Reduza o tamanho e tente novamente.');
 return (await apiFetch<{url:string}>('/imagens',{method:'POST',body:JSON.stringify({data})})).url;
}
export function DigitalImages({images,onChange,onBusyChange,max=12,label='Imagens'}:{images:string[];onChange:(values:string[])=>void;onBusyChange?:(busy:boolean)=>void;max?:number;label?:string}) {
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[url,setUrl]=useState('');
 async function run(action:()=>Promise<string[]>){setBusy(true);onBusyChange?.(true);setError('');try{onChange(await action());setUrl('');}catch(e:any){setError(e.message||'Não foi possível carregar a imagem.');}finally{setBusy(false);onBusyChange?.(false);}}
 function move(i:number,d:number){const next=[...images];[next[i],next[i+d]]=[next[i+d],next[i]];onChange(next);}
 return <fieldset disabled={busy} className="space-y-3 min-w-0"><legend className="font-semibold mb-2">{label}</legend><label className="block text-sm">Carregar do computador<input aria-label={label+' do computador'} type="file" accept="image/jpeg,image/png,image/webp" multiple={max>1} disabled={images.length>=max||busy} className="block mt-2 w-full text-sm" onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(files.length)void run(async()=>{if(images.length+files.length>max)throw new Error('Limite de '+max+' imagens.');const next=[...images];for(const f of files)next.push(await upload(f));return next;});}}/></label><label className="block text-sm">URL HTTPS ou data:image<textarea aria-label={label+' por URL ou data:image'} rows={2} className="w-full border rounded-xl p-3 mt-1 text-xs break-all" placeholder="https://... ou data:image/jpeg;base64,..." value={url} onChange={e=>setUrl(e.target.value)}/></label><button type="button" disabled={busy||!url.trim()||images.length>=max} className="border rounded-xl px-4 py-2 disabled:opacity-40" onClick={()=>void run(async()=>{const value=url.trim();let image=value;if(value.startsWith('data:')){if(value.length>28000000||!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=\s]+$/.test(value))throw new Error('Use data:image/jpeg, png ou webp em base64 (até 20 MB).');const blob=await (await fetch(value)).blob();image=await upload(new File([blob],'imagem',{type:blob.type}));}else{try{if(new URL(value).protocol!=='https:')throw new Error();}catch{throw new Error('Informe uma URL HTTPS válida ou uma imagem data:image.');}}return [...images,image];})}>Adicionar imagem</button>{busy&&<p role="status" className="text-sm">Carregando imagem…</p>}{error&&<p role="alert" className="text-red-700 text-sm">{error}</p>}<div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{images.map((src,i)=><div key={i} className="border rounded-xl p-2 min-w-0"><img src={src} alt={label+' '+(i+1)} className="w-full h-24 object-contain"/><p className="text-xs my-2">{max>1?(i===0?'1 · Principal':String(i+1)):'Imagem atual'}</p><div className="flex flex-wrap gap-2 text-sm"><button type="button" aria-label={'Mover imagem '+(i+1)+' para antes'} disabled={i===0} onClick={()=>move(i,-1)} className="border px-2 rounded disabled:opacity-30">←</button><button type="button" aria-label={'Mover imagem '+(i+1)+' para depois'} disabled={i===images.length-1} onClick={()=>move(i,1)} className="border px-2 rounded disabled:opacity-30">→</button><button type="button" className="text-red-700 underline" onClick={()=>onChange(images.filter((_,n)=>n!==i))}>Remover</button></div></div>)}</div></fieldset>;
}
