import { useEffect, useState, useRef, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { ChevronLeft, ChevronRight, Pause, Play, Download } from 'lucide-react';
import { apiFetch } from '../lib/api';
export type DigitalSettings={nome:string;logo:string;titulo:string;subtitulo:string;rodape_titulo:string;rodape_texto:string;contato:string;direitos:string;banner_intervalo:number;banner_automatico:boolean;banners:{id:string;imagem:string;titulo:string;ativo:boolean}[]};
export const defaultDigitalSettings:DigitalSettings={nome:'Catálogo digital',logo:'',titulo:'Escolha, pague e baixe',subtitulo:'Arquivos para seus projetos. Download após a confirmação do pagamento.',rodape_titulo:'Catálogo digital',rodape_texto:'',contato:'',direitos:'',banner_intervalo:4,banner_automatico:true,banners:[]};
export function DigitalFrame({children,catalog=false}:{children:ReactNode;catalog?:boolean}) {
 const [settings,setSettings]=useState(defaultDigitalSettings);
 useEffect(()=>{let alive=true;apiFetch<DigitalSettings>('/digital/configuracoes').then(s=>{if(alive)setSettings(s);}).catch(()=>{});return()=>{alive=false;};},[]);
 useEffect(()=>{const old=document.title;document.title=settings.nome;return()=>{document.title=old;};},[settings.nome]);
 return <div className="min-h-screen bg-slate-50 flex flex-col"><header className="bg-white border-b"><div className="max-w-6xl mx-auto px-4 py-5"><Link to="/digitais" className="inline-flex items-center gap-3" aria-label={settings.nome}>{settings.logo?<img className="max-w-[240px] max-h-20 object-contain" src={settings.logo} alt={settings.nome}/>:<span className="text-2xl font-bold text-primary">{settings.nome}</span>}</Link></div></header><main className="max-w-6xl w-full mx-auto px-4 py-8 flex-1">{catalog&&<><DigitalBanners settings={settings}/><h1 className="text-3xl font-bold mt-2 break-words">{settings.titulo}</h1><p className="text-slate-600 mt-3 whitespace-pre-wrap break-words">{settings.subtitulo}</p></>}{children}</main><footer className="bg-slate-900 text-slate-200 mt-8"><div className="max-w-6xl mx-auto px-4 py-10 space-y-4 break-words"><h2 className="text-lg font-semibold text-white">{settings.rodape_titulo}</h2>{settings.rodape_texto&&<p className="whitespace-pre-wrap text-sm max-w-3xl">{settings.rodape_texto}</p>}{settings.contato&&<p className="whitespace-pre-wrap text-sm">{settings.contato}</p>}{settings.direitos&&<p className="text-xs text-slate-400 border-t border-slate-700 pt-5">{settings.direitos}</p>}</div></footer></div>;
}
export function DigitalBanners({settings}:{settings:DigitalSettings}) {
 const banners=settings.banners.filter(b=>b.ativo&&b.imagem),[index,setIndex]=useState(0),[paused,setPaused]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches);
 useEffect(()=>{if(banners.length<2||paused||!settings.banner_automatico)return;const timer=setInterval(()=>setIndex(i=>(i+1)%banners.length),settings.banner_intervalo*1000);return()=>clearInterval(timer);},[banners.length,paused,settings.banner_intervalo,settings.banner_automatico]);
 if(!banners.length)return null;const current=index%banners.length,move=(d:number)=>setIndex(i=>(i+d+banners.length)%banners.length);
 return <section aria-label="Banners do catálogo digital" className="relative rounded-2xl overflow-hidden mb-8 bg-slate-100 aspect-[2/1] sm:aspect-[4/1]"><img src={banners[current].imagem} alt={banners[current].titulo||'Novidades do catálogo digital'} className="h-full w-full object-cover"/>{banners.length>1&&<><button type="button" aria-label="Banner anterior" onClick={()=>move(-1)} className="absolute top-1/2 left-2 -translate-y-1/2 rounded-full bg-black/60 text-white p-2"><ChevronLeft size={20}/></button><button type="button" aria-label="Próximo banner" onClick={()=>move(1)} className="absolute top-1/2 right-2 -translate-y-1/2 rounded-full bg-black/60 text-white p-2"><ChevronRight size={20}/></button><div className="absolute bottom-3 left-3 right-14 flex justify-center flex-wrap gap-2">{banners.map((b,i)=><button key={b.id} aria-label={'Mostrar banner '+(i+1)} aria-current={i===current} onClick={()=>setIndex(i)} className={'w-3 h-3 rounded-full border border-black/20 '+(i===current?'bg-white':'bg-white/40')}/>)}</div>{settings.banner_automatico&&<button type="button" aria-label={paused?'Reproduzir banners':'Pausar banners'} onClick={()=>setPaused(!paused)} className="absolute bottom-2 right-2 p-2 bg-black/60 text-white rounded-full">{paused?<Play size={16}/>:<Pause size={16}/>}</button>}</>}</section>;
}
export function DigitalGallery({images,name}:{images:string[];name:string}) {
 const dialog=useRef<HTMLDialogElement>(null);const [index,setIndex]=useState(0),[expanded,setExpanded]=useState(false);const current=images.length?index%images.length:0;
 useEffect(()=>{if(!expanded)return;dialog.current?.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;};},[expanded]);
 if(!images.length)return <div className="aspect-square grid place-items-center bg-blue-50 text-primary"><Download size={42}/></div>;
 return <div><button type="button" className="block w-full" aria-label={'Ampliar imagem de '+name} onClick={()=>setExpanded(true)}><img src={images[current]} alt={name+' — foto '+(current+1)} className="aspect-square object-contain w-full bg-white" loading="lazy" referrerPolicy="no-referrer"/></button>{images.length>1&&<div className="flex gap-2 p-2 overflow-x-auto">{images.map((image,i)=><button type="button" key={i} aria-label={'Ver foto '+(i+1)+' de '+name} aria-pressed={current===i} onClick={()=>setIndex(i)} className={'shrink-0 rounded border-2 overflow-hidden '+(current===i?'border-blue-700':'border-transparent')}><img src={image} alt="" className="w-10 h-10 object-cover" loading="lazy"/></button>)}</div>}{expanded&&<dialog ref={dialog} onCancel={()=>setExpanded(false)} onClose={()=>setExpanded(false)} className="fixed inset-0 z-50 m-0 w-full h-full max-w-none max-h-none bg-black/90 text-white flex flex-col items-center justify-center p-4" aria-label={'Imagens de '+name} onClick={()=>setExpanded(false)}><button autoFocus type="button" className="absolute right-4 top-4 bg-white text-black rounded-xl px-4 py-2" onClick={()=>setExpanded(false)}>Fechar</button><img onClick={e=>e.stopPropagation()} src={images[current]} alt={name+' — foto '+(current+1)} className="max-h-[75vh] max-w-full object-contain"/>{images.length>1&&<div className="flex items-center gap-5 mt-4" onClick={e=>e.stopPropagation()}><button aria-label="Foto anterior" onClick={()=>setIndex(i=>(i-1+images.length)%images.length)} className="border rounded-lg p-3"><ChevronLeft/></button><span>{current+1} / {images.length}</span><button aria-label="Próxima foto" onClick={()=>setIndex(i=>(i+1)%images.length)} className="border rounded-lg p-3"><ChevronRight/></button></div>}</dialog>}</div>;
}
