import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import QRCode from 'qrcode';
import { apiFetch, formatMoney } from '../lib/api';
export type DigitalPurchase={id:string;nome:string;valor_centavos:number;status:string;gateway?:string;teste?:boolean;checkout_url?:string;download_url?:string;pix_codigo?:string;pix_expira_em?:string;pode_tentar_novamente?:boolean};
export function recentDigitalPurchases():{id:string;token:string;nome:string}[]{
 try{const rows=JSON.parse(localStorage.getItem('compras_digitais')||'[]');return Array.isArray(rows)?rows.filter(p=>p&&typeof p.id==='string'&&typeof p.token==='string').slice(0,30):[];}catch{return [];}
}
export function DigitalCheckout({product,onClose}:{product:{id:string;nome:string;preco_centavos:number};onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),inFlight=useRef(false);
 const [config,setConfig]=useState<{gateway:string;habilitado:boolean;teste:boolean}|null>(null);
 const [form,setForm]=useState({nome:'',email:'',documento:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState<{id:string;token:string}|null>(null);
 useEffect(()=>{dialog.current?.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';apiFetch<any>('/digital/pagamento-configuracao').then(setConfig).catch(e=>setError(e.message));return()=>{document.body.style.overflow=old;};},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(inFlight.current||!config?.habilitado)return;inFlight.current=true;setBusy(true);setError('');
 const next=attempt||{id:crypto.randomUUID(),token:Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('')};setAttempt(next);
 try{
  localStorage.setItem('compras_digitais',JSON.stringify([{...next,nome:product.nome},...recentDigitalPurchases().filter(p=>p.id!==next.id)].slice(0,30)));
  const created=await apiFetch<DigitalPurchase>('/digital/checkout',{method:'POST',body:JSON.stringify({...next,produto_id:product.id,...(config.gateway==='uvvipay'?{cliente:form}:{})})});
  sessionStorage.setItem('digital_checkout_'+next.id,JSON.stringify(created));
  window.location.assign('/digitais/pedido/'+next.id+'#'+next.token);
 }catch(e:any){setError(e.message);}finally{inFlight.current=false;setBusy(false);}}
 return <dialog ref={dialog} onCancel={e=>{if(busy)e.preventDefault();else onClose();}} className="fixed inset-0 m-auto w-[calc(100%_-_2rem)] max-w-lg max-h-[90dvh] overflow-y-auto rounded-2xl p-5 sm:p-7 backdrop:bg-black/60"><div className="flex gap-4 items-start justify-between"><h2 className="font-bold text-xl">Finalizar compra</h2><button type="button" disabled={busy} onClick={onClose} aria-label="Fechar compra" className="border px-3 py-1 rounded-lg">×</button></div><p className="mt-4 font-semibold">{product.nome}</p><p className="text-2xl font-bold mt-1">{formatMoney(product.preco_centavos/100)}</p>{config?.teste&&<p className="mt-4 p-3 bg-amber-50 text-amber-800 text-sm">Ambiente de testes. O download real não será liberado.</p>}{error&&<p role="alert" className="text-red-700 my-4">{error}</p>}{!config&&!error&&<p className="my-4">Preparando compra…</p>}{config&&!config.habilitado&&<p className="my-4">Os pagamentos estão temporariamente indisponíveis. Tente mais tarde.</p>}<form onSubmit={submit} className="mt-5 space-y-4"><fieldset disabled={busy||!config?.habilitado} className="space-y-4">{config?.gateway==='uvvipay'&&<><label className="block text-sm font-medium">Nome completo<input required minLength={3} maxLength={255} autoComplete="name" className="w-full border rounded-xl p-3 mt-1" value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></label><label className="block text-sm font-medium">E-mail<input required type="email" maxLength={320} autoComplete="email" className="w-full border rounded-xl p-3 mt-1" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="block text-sm font-medium">CPF ou CNPJ<input required inputMode="numeric" maxLength={18} className="w-full border rounded-xl p-3 mt-1" value={form.documento} onChange={e=>setForm({...form,documento:e.target.value})}/></label><p className="text-xs text-slate-500">Esses dados são enviados à UvviPay para processar o pagamento. A entrega do arquivo acontece na página da compra.</p></>}<button disabled={busy||!config?.habilitado} className="w-full bg-primary text-white font-semibold rounded-xl p-3 disabled:opacity-50">{busy?'Preparando pagamento…':config?.gateway==='livepix'?'Continuar com LivePix':'Gerar Pix com UvviPay'}</button></fieldset></form>{attempt&&error&&<Link className="block underline text-sm mt-4" to={'/digitais/pedido/'+attempt.id+'#'+attempt.token}>Consultar esta tentativa de compra</Link>}</dialog>;
}
export type DigitalHistoryItem={id:string;nome:string;valor_centavos:number;status:string;created_at:string;pago_em?:string|null;pode_baixar?:boolean};
export function DigitalPurchaseHistory(){
 const [documento,setDocumento]=useState(''),[items,setItems]=useState<DigitalHistoryItem[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loadingId,setLoadingId]=useState(''),[searched,setSearched]=useState(false);
 async function search(e:React.FormEvent){e.preventDefault();setBusy(true);setSearched(true);setError('');try{setItems(await apiFetch<DigitalHistoryItem[]>('/digital/compras',{method:'POST',body:JSON.stringify({documento})}));}catch(e:any){setItems([]);setError(e.message);}finally{setBusy(false);}}
 async function download(item:DigitalHistoryItem){setLoadingId(item.id);setError('');try{const result=await apiFetch<{download_url:string}>('/digital/compras/'+item.id+'/baixar',{method:'POST',body:JSON.stringify({documento})});window.open(result.download_url,'_blank','noopener,noreferrer');}catch(e:any){setError(e.message);}finally{setLoadingId('');}}
 return <section className="mt-10 rounded-2xl border bg-white p-5 sm:p-6"><h2 className="text-xl font-bold">Acessar minhas compras</h2><p className="text-sm text-slate-600 mt-1">Informe o CPF ou CNPJ usado no pagamento para encontrar seus arquivos.</p><form onSubmit={search} className="mt-4 flex flex-col sm:flex-row gap-3"><input required inputMode="numeric" maxLength={18} value={documento} onChange={e=>{setDocumento(e.target.value);setSearched(false);}} className="flex-1 border rounded-xl p-3" placeholder="CPF ou CNPJ" aria-label="CPF ou CNPJ da compra"/><button disabled={busy} className="rounded-xl bg-primary px-5 py-3 text-white font-semibold disabled:opacity-50">{busy?'Consultando…':'Consultar compras'}</button></form>{error&&<p role="alert" className="text-red-700 mt-3">{error}</p>}{items.length>0&&<div className="mt-5 space-y-3">{items.map(item=><div key={item.id} className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 rounded-xl border p-4"><div><p className="font-semibold">{item.nome}</p><p className="text-sm text-slate-600">{formatMoney(item.valor_centavos/100)} · {new Date(item.pago_em||item.created_at).toLocaleDateString('pt-BR')}</p></div><button onClick={()=>download(item)} disabled={loadingId===item.id} className="inline-flex justify-center rounded-xl bg-primary px-4 py-2 text-white font-semibold disabled:opacity-50">{loadingId===item.id?'Preparando…':'Baixar arquivo'}</button></div>)}</div>}{!busy&&searched&&items.length===0&&<p className="text-sm text-slate-500 mt-4">Nenhuma compra paga encontrada para este documento.</p>}</section>;
}
export function DigitalPix({order}:{order:DigitalPurchase}){
 const [image,setImage]=useState(''),[notice,setNotice]=useState(''),[now,setNow]=useState(Date.now());
 useEffect(()=>{let alive=true;setImage('');if(order.pix_codigo)QRCode.toDataURL(order.pix_codigo,{width:320,margin:4,errorCorrectionLevel:'M'}).then(s=>{if(alive)setImage(s);}).catch(()=>{if(alive)setNotice('Use o Pix Copia e Cola abaixo.');});return()=>{alive=false;};},[order.pix_codigo]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const end=order.pix_expira_em?Date.parse(order.pix_expira_em):NaN,remaining=Math.max(0,Math.ceil((end-now)/1000));
 const expired=Number.isFinite(end)&&remaining===0;
 async function copy(){try{await navigator.clipboard.writeText(order.pix_codigo||'');setNotice('Pix copiado. Cole no aplicativo do seu banco.');}catch{setNotice('Selecione e copie o código abaixo.');}}
 return <section className="space-y-4"><p className="font-semibold">Pague com Pix · UvviPay</p>{expired?<p className="bg-amber-50 text-amber-900 p-3 rounded-xl">O prazo informado para este Pix terminou. Se já pagou, consulte a confirmação antes de iniciar outra compra.</p>:<>{image&&<img className="w-64 max-w-full mx-auto" src={image} alt="QR Code Pix desta compra"/>}{Number.isFinite(end)&&<p className="text-sm text-center">Validade: {Math.floor(remaining/60)}min {String(remaining%60).padStart(2,'0')}s</p>}<label className="block text-sm">Pix Copia e Cola<textarea readOnly value={order.pix_codigo||''} className="mt-1 w-full border rounded-xl p-3 text-xs break-all" rows={3} onFocus={e=>e.target.select()}/></label><button className="w-full bg-primary text-white rounded-xl p-3 font-semibold" onClick={copy}>Copiar código Pix</button></>}{notice&&<p role="status" className="text-sm">{notice}</p>}<p className="text-sm text-slate-600">Após pagar, mantenha esta página aberta. O download será liberado quando o pagamento for confirmado.</p></section>;
}
