import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
const root=new URL('../../database/migrations/',import.meta.url).pathname;
await db.exec('create role anon; create role authenticated; create role service_role; create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);');
await db.exec(readFileSync(root+'001_init.sql','utf8').replace('create extension if not exists "pgcrypto";',''));
await db.exec(readFileSync(root+'003_pedidos_documentos_permissoes.sql','utf8'));
await db.exec(readFileSync(root+'009_fluxo_caixa.sql','utf8'));
await db.exec(readFileSync(root+'011_pdv_producao.sql','utf8'));
await db.exec(readFileSync(root+'006_modal_padrao_variacoes_produtos.sql','utf8'));
await db.exec(readFileSync(root+'012_catalogo_pedidos.sql','utf8'));
const id='11111111-1111-4111-8111-111111111111';
await db.query("insert into produtos(id,nome,descricao,preco,imagem_principal,slug,sku,variacoes) values($1,'Pasta','Pasta A4',90,'geral.jpg','pasta','pasta',$2)",[id,JSON.stringify([{id:'fosco',nome:'Fosco',preco:100,opcoes:{Acabamento:'Fosco',Quantidade:'100 unidades'},imagens:['fosco.jpg']}])]);
const data={chave_checkout:'22222222-2222-4222-8222-222222222222',tipo_entrega:'retirada',cliente_nome:'Teste',cliente_telefone:'88999999999',endereco_entrega:'Retirada',items:[{produto_id:id,variacao_id:'fosco',quantidade:2}],total:1};
const call=async d=>(await db.query('select criar_pedido_catalogo($1::jsonb) result',[JSON.stringify(d)])).rows[0].result;
const a=await call(data);assert.equal(a.total,200);assert.equal(a.valor_restante,200);assert.equal(a.itens_snapshot[0].imagem_principal,'fosco.jpg');
const b=await call(data);assert.equal(a.id,b.id);assert.equal((await db.query('select count(*)::int n from itens_pedido')).rows[0].n,1);
await assert.rejects(()=>call({...data,chave_checkout:'33333333-3333-4333-8333-333333333333',items:[...data.items,{produto_id:id,variacao_id:'invalida',quantidade:1}]}));
assert.equal((await db.query('select count(*)::int n from pedidos')).rows[0].n,1);
await db.query("update produtos set preco=500, nome='Alterado',ativo=false where id=$1",[id]);
assert.equal((await call(data)).itens_snapshot[0].nome,'Pasta');
await assert.rejects(()=>call({...data,chave_checkout:'44444444-4444-4444-8444-444444444444'}));
await db.exec(readFileSync(root+'013_catalogo_pdv.sql','utf8'));
const migrated=(await db.query('select * from pedidos where id=$1',[a.id])).rows[0];
assert.match(migrated.numero_pedido,/^WC[0-9]{6}$/);assert.equal(migrated.numero_pedido_anterior,a.numero_pedido);
await db.exec(readFileSync(root+'013_catalogo_pdv.sql','utf8'));
assert.equal((await db.query('select numero_pedido from pedidos where id=$1',[a.id])).rows[0].numero_pedido,migrated.numero_pedido);
const operator='99999999-9999-4999-8999-999999999999';
await db.query("insert into users(id,email,nome,senha,role) values($1,'teste@teste.com','Operador','teste','admin')",[operator]);
const avulso=async(d)=>(await db.query('select criar_pedido_avulso($1::jsonb,$2::uuid) result',[JSON.stringify(d),operator])).rows[0].result;
const blank=await avulso({chave_checkout:'55555555-5555-4555-8555-555555555555'});
assert.equal(blank.total,0);assert.equal(blank.cliente_nome,'Cliente não informado');assert.match(blank.numero_pedido,/^WC[0-9]{6}$/);
const payload={chave_checkout:'66666666-6666-4666-8666-666666666666',quantidade:3,preco_unitario:10,desconto:5,valor_pago:7,data_pedido:'2026-09-25',data_entrega:'2026-09-30',descricao:'Sacolas'};
const custom=await avulso(payload);assert.equal(custom.total,25);assert.equal(custom.valor_restante,18);assert.equal(custom.status_pagamento,'parcial');
assert.equal((await avulso(payload)).id,custom.id);
assert.equal((await db.query('select count(*)::int n from caixa_movimentacoes where pedido_id=$1',[custom.id])).rows[0].n,1);
const manualTotal=await avulso({...payload,chave_checkout:'77777777-7777-4777-8777-777777777777',valor_total:100,valor_pago:200});assert.equal(manualTotal.total,95);assert.equal(manualTotal.valor_restante,0);
const variations=[{id:'v1',opcoes:{Acabamento:'Fosco',Quantidade:'100'},imagens:['fosco.jpg']},{id:'v2',opcoes:{Acabamento:'Fosco',Quantidade:'200'},imagens:['incorreta.jpg']},{id:'v3',opcoes:{Acabamento:'Brilho',Quantidade:'100'},imagens:['brilho.jpg']}];
await db.query('update produtos set variacoes=$1 where id=$2',[JSON.stringify(variations),id]);
const synced=(await db.query('select variacoes from produtos where id=$1',[id])).rows[0].variacoes;assert.deepEqual(synced[0].imagens,synced[1].imagens);assert.notDeepEqual(synced[0].imagens,synced[2].imagens);
assert.equal((await db.query('select * from catalogo_vendas()')).rows.length,0);
await db.query("update pedidos set status='confirmado' where id=$1",[a.id]);assert.equal(Number((await db.query('select * from catalogo_vendas()')).rows[0].vendidos),2);
await db.query("update pedidos set status='cancelado' where id=$1",[a.id]);assert.equal((await db.query('select * from catalogo_vendas()')).rows.length,0);
console.log('PASS V9: numeração curta, alias antigo, migração reaplicável, avulso vazio, descontos/saldo, caixa sem duplicidade, total manual, galerias por acabamento e ranking.');
console.log('PASS: preço do servidor, saldo, foto, idempotência, rollback, histórico imutável e produto inativo.');
await db.close();
