import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
const root=new URL('../../database/migrations/',import.meta.url).pathname;
await db.exec('create role anon; create role authenticated; create role service_role; create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);');
await db.exec(readFileSync(root+'001_init.sql','utf8').replace('create extension if not exists "pgcrypto";',''));
await db.exec("alter table pedidos add valor_entrada numeric default 0, add valor_restante numeric default 0;");
await db.exec(readFileSync(root+'006_modal_padrao_variacoes_produtos.sql','utf8'));
await db.exec(readFileSync(root+'012_catalogo_pedidos.sql','utf8'));
const id='11111111-1111-4111-8111-111111111111';
await db.query("insert into produtos(id,nome,descricao,preco,imagem_principal,slug,sku,variacoes) values($1,'Pasta','Pasta A4',90,'geral.jpg','pasta','pasta',$2)",[id,JSON.stringify([{id:'fosco',nome:'Fosco',preco:100,opcoes:{Acabamento:'Fosco',Quantidade:'100 unidades'},imagens:['fosco.jpg']}])]);
const data={chave_checkout:'22222222-2222-4222-8222-222222222222',cliente_nome:'Teste',cliente_telefone:'88999999999',endereco_entrega:'Retirada',items:[{produto_id:id,variacao_id:'fosco',quantidade:2}],total:1};
const call=async d=>(await db.query('select criar_pedido_catalogo($1::jsonb) result',[JSON.stringify(d)])).rows[0].result;
const a=await call(data);assert.equal(a.total,200);assert.equal(a.valor_restante,200);assert.equal(a.itens_snapshot[0].imagem_principal,'fosco.jpg');
const b=await call(data);assert.equal(a.id,b.id);assert.equal((await db.query('select count(*)::int n from itens_pedido')).rows[0].n,1);
await assert.rejects(()=>call({...data,chave_checkout:'33333333-3333-4333-8333-333333333333',items:[...data.items,{produto_id:id,variacao_id:'invalida',quantidade:1}]}));
assert.equal((await db.query('select count(*)::int n from pedidos')).rows[0].n,1);
await db.query("update produtos set preco=500, nome='Alterado',ativo=false where id=$1",[id]);
assert.equal((await call(data)).itens_snapshot[0].nome,'Pasta');
await assert.rejects(()=>call({...data,chave_checkout:'44444444-4444-4444-8444-444444444444'}));
console.log('PASS: preço do servidor, saldo, foto, idempotência, rollback, histórico imutável e produto inativo.');
await db.close();
