import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Search, SlidersHorizontal, PackageSearch, ChevronDown } from 'lucide-react';
import { apiFetch, normalizeProduct, normalizeCategory, Product, Category } from '../lib/api';
import { ProductCard } from '../components/ProductCard';
import { PromotionBanner, Banner, parseBanners } from '../components/PromotionBanner';
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const options=(p:Product)=> (p.variacoes||[]).filter(v=>v.ativo!==false).map(v=>({...v.opcoes,Material:v.opcoes?.Material||'',Acabamento:v.opcoes?.Acabamento||v.acabamento||'',Tamanho:v.opcoes?.Tamanho||v.tamanho||''}));
const minPrice=(p:Product)=>{const v=(p.variacoes||[]).filter(v=>v.ativo!==false&&v.preco>0);return v.length?Math.min(...v.map(v=>v.preco)):p.preco;};
export function Catalogo(){
 const [params,setParams]=useSearchParams();const [products,setProducts]=useState<Product[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [banners,setBanners]=useState<Banner[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [filterOpen,setFilterOpen]=useState(false);
 const q=params.get('q')||'';const category=params.get('categoria')||'';const material=params.get('material')||'';const finish=params.get('acabamento')||'';const size=params.get('tamanho')||'';const sort=params.get('ordenar')||'vendidos';
 function set(key:string,value:string){setParams(prev=>{const next=new URLSearchParams(prev);if(value)next.set(key,value);else next.delete(key);if(key==='categoria'){next.delete('material');next.delete('acabamento');next.delete('tamanho');}if(key==='material'){next.delete('acabamento');next.delete('tamanho');}if(key==='acabamento')next.delete('tamanho');return next;},{replace:true});}
 async function load(){setLoading(true);setError('');try{const [all,cats,config]=await Promise.all([(async()=>{const data:Product[]=[];for(let page=1;;page++){const batch=await apiFetch<{data:unknown[]}>(`/produtos?limit=100&page=${page}`);data.push(...batch.data.map(normalizeProduct));if(batch.data.length<100)break;}return data;})(),apiFetch<any[]>('/categorias'),apiFetch<Record<string,string>>('/configuracoes')]);setProducts(all);setCategories(cats.map(normalizeCategory));setBanners(parseBanners(config.catalogo_banners));}catch(e:any){setError(e.message||'Não foi possível carregar o catálogo.');}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 const base=useMemo(()=>products.filter(p=>!category||p.categoria_slug===category||p.categoria_id===category),[products,category]);
 function values(key:string){const list=base.flatMap(options).filter(o=>(key==='Material'||!material||o.Material===material)&&(key!=='Tamanho'||!finish||o.Acabamento===finish));return [...new Set(list.map(o=>(o as Record<string,string>)[key]).filter(Boolean))].sort();}
 const visible=useMemo(()=>base.filter(p=>{
  const variants=options(p);if((material||finish||size)&&!variants.some(o=>(!material||o.Material===material)&&(!finish||o.Acabamento===finish)&&(!size||o.Tamanho===size)))return false;
  return !q||normalize([p.nome,p.descricao,p.categoria_nome,p.sku,...variants.flatMap(Object.values)].join(' ')).includes(normalize(q));
 }).sort((a,b)=>{
  if(sort==='menor_preco')return minPrice(a)-minPrice(b);if(sort==='maior_preco')return minPrice(b)-minPrice(a);if(sort==='nome')return a.nome.localeCompare(b.nome,'pt-BR');if(sort==='recentes')return String((b as any).created_at).localeCompare(String((a as any).created_at));if(sort==='destaque')return Number(b.destaque)-Number(a.destaque);
  return (Number(b.vendidos||0)-Number(a.vendidos||0))||Number(b.destaque)-Number(a.destaque)||a.nome.localeCompare(b.nome,'pt-BR');
 }),[base,q,material,finish,size,sort]);
 return <div className="max-w-7xl mx-auto px-3 sm:px-5 py-4">
 <PromotionBanner banners={banners}/>
 <div className="flex items-center justify-between gap-3 rounded-xl bg-primary px-4 py-3 mb-4 text-white"><span className="text-sm font-semibold">Já fez seu pedido?</span><Link to="/acompanhar" className="inline-flex gap-2 items-center text-sm font-bold text-gold"><PackageSearch size={18}/>Acompanhar pedido</Link></div>
 <h1 className="sr-only">Catálogo Gráfica W Criações</h1>
 <div className="flex gap-2 mb-3"><label className="relative flex-1"><span className="sr-only">Buscar produtos</span><Search size={18} className="absolute left-3 top-3.5 text-gray-400"/><input className="input pl-10" value={q} onChange={e=>set('q',e.target.value)} placeholder="Buscar produtos…"/></label><button aria-expanded={filterOpen} aria-controls="catalog-filters" className={`btn px-3 ${filterOpen?'btn-primary':'btn-outline'}`} onClick={()=>setFilterOpen(!filterOpen)}><SlidersHorizontal size={18}/><span className="hidden sm:inline">Filtros</span><ChevronDown size={16} className={filterOpen?'rotate-180':''}/></button></div>
 {filterOpen&&<div id="catalog-filters" className="rounded-xl border p-3 mb-4 grid sm:grid-cols-2 lg:grid-cols-4 gap-3 bg-gray-50">{[{label:'Material',key:'material',value:material},{label:'Acabamento',key:'acabamento',value:finish},{label:'Tamanho',key:'tamanho',value:size}].map(f=><label className="text-sm font-semibold" key={f.key}>{f.label}<select className="input mt-1" value={f.value} onChange={e=>set(f.key,e.target.value)}><option value="">Todos</option>{values(f.label).map(v=><option key={v}>{v}</option>)}</select></label>)}<label className="text-sm font-semibold">Ordenar<select className="input mt-1" value={sort} onChange={e=>set('ordenar',e.target.value)}><option value="vendidos">Mais vendidos</option><option value="destaque">Destaques</option><option value="menor_preco">Menor preço</option><option value="maior_preco">Maior preço</option><option value="recentes">Mais recentes</option><option value="nome">Nome A–Z</option></select></label><button className="text-sm underline text-left" onClick={()=>setParams({})}>Limpar filtros</button></div>}
 <div className="flex gap-2 overflow-x-auto pb-3 mb-2" aria-label="Categorias"><button className={`shrink-0 rounded-lg border px-3 py-2 text-xs font-bold ${!category?'bg-primary text-white':'bg-white'}`} onClick={()=>set('categoria','')}>Todos</button>{categories.map(c=><button key={c.id} onClick={()=>set('categoria',c.slug||c.id)} className={`shrink-0 inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold ${category===(c.slug||c.id)?'bg-primary text-white':'bg-white text-primary'}`}>{c.imagem_url&&<img src={c.imagem_url} alt="" className="h-7 w-7 object-cover rounded-md"/>}{c.nome}</button>)}</div>
 {loading?<div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-3">{Array.from({length:10},(_,i)=><div key={i} className="h-64 bg-gray-100 rounded-xl animate-pulse"/>)}</div>:error?<div role="alert" className="card p-6"><p>{error}</p><button className="btn btn-primary mt-3" onClick={load}>Tentar novamente</button></div>:visible.length?<div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-3 sm:gap-4">{visible.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="card p-8 text-center">Nenhum produto encontrado.<button className="block mx-auto underline mt-3" onClick={()=>setParams({})}>Limpar filtros</button></div>}
 </div>;
}
export default Catalogo;
