import { formatMoney } from './api';
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const date=(s:any)=>s?String(s).slice(0,10).split('-').reverse().join('/'):'A combinar';
export function renderElginLabel(popup:Window, data:any, width=100,height=150){
 width=Math.max(40,Math.min(108,Number(width)||100));height=Math.max(40,Math.min(300,Number(height)||150));
 const order=data.pedido;const items=order.itens_snapshot?.length?order.itens_snapshot:(data.itens||[]).map((i:any)=>({...i,nome:i.especificacoes?.nome_produto||'Produto',especificacoes_selecionadas:i.especificacoes}));
 const details=items.map((i:any)=>`<div class="item"><b>${esc(i.quantidade)} × ${esc(i.nome)}</b><div>${Object.entries(i.especificacoes_selecionadas||{}).filter(([k])=>!k.startsWith('_')&&!['Variação','nome_produto','Preço da variação'].includes(k)).map(([k,v])=>`${esc(k)}: ${esc(v)}`).join(' · ')}</div><div>Unit.: ${esc(formatMoney(Number(i.preco_unitario)||0))} · Total: ${esc(formatMoney(Number(i.valor_total??(i.quantidade*i.preco_unitario))||0))}</div></div>`).join('');
 popup.document.open();popup.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Pedido ${esc(order.numero_pedido)}</title><style>@page{size:${width}mm ${height}mm;margin:3mm}*{box-sizing:border-box}body{font:11px Arial,sans-serif;color:#000;width:${width-6}mm;margin:0 auto;overflow-wrap:anywhere}h1{font-size:16px;margin:4px 0}h2{font-size:14px;margin:6px 0}.row{display:flex;justify-content:space-between;gap:4mm;margin:4px 0}.item{border-top:1px dashed #000;padding:6px 0;white-space:pre-wrap}header,footer{break-inside:avoid}.total{font-size:14px;font-weight:bold}button{margin:12px 0;padding:10px;width:100%}@media print{button,.help{display:none}}</style></head><body><button onclick="window.print()">Imprimir na Elgin L42 Pro</button><p class="help">Selecione a Elgin instalada no computador. Papel ${width} × ${height} mm, escala 100%, sem cabeçalhos e rodapés. Conteúdo longo poderá ocupar mais etiquetas.</p><header><h1>${esc(data.empresa?.nome||'Gráfica W Criações')}</h1><h2>Pedido ${esc(order.numero_pedido)}</h2><div>Data: ${date(order.data_pedido||order.created_at)}</div><div>Entrega: ${date(order.prazo_entrega||order.data_entrega_estimada)}</div><p><b>${esc(order.cliente_nome||'Cliente não informado')}</b><br>${esc(order.cliente_telefone||'')}</p></header>${details}<footer><div class="row"><span>Desconto</span><b>${esc(formatMoney(Number(order.desconto)||0))}</b></div><div class="row total"><span>Total</span><span>${esc(formatMoney(Number(order.total)||0))}</span></div><div class="row"><span>Pago</span><span>${esc(formatMoney(Number(order.valor_entrada)||0))}</span></div><div class="row"><span>Restante</span><b>${esc(formatMoney(Number(order.valor_restante)||0))}</b></div></footer></body></html>`);popup.document.close();popup.focus();setTimeout(()=>popup.print(),250);
}
